"""
constants.py
============
Single source of truth for all string literals used across the AETHEL pipeline.

Centralising constants here eliminates copy-paste bugs when column names,
feature lists, or label strings must be referenced in multiple modules
(Python preprocessing, dashboard, future calibration / fairness layers).

Usage
-----
    from src.utils.constants import Columns, Features, RiskLabels
"""

# ---------------------------------------------------------------------------
# Data column names
# ---------------------------------------------------------------------------

class Columns:
    """Column names as they appear in the analytical cohort CSV."""

    # --- Patient identifiers ---
    PATIENT_ID: str = "patient_id"

    # --- Clinical / demographic ---
    AGE: str = "age"
    BMI: str = "bmi"
    IS_SMOKER: str = "is_smoker"
    GENOMIC_RISK_SCORE: str = "genomic_risk_score"
    TOWNSEND_INDEX: str = "townsend_index"

    # --- Survival outcomes ---
    MONTHS_OBSERVED: str = "months_observed"
    EVENT_OCCURRED: str = "event_occurred"

    # --- Environmental exposures (engineered) ---
    AVG_PM25_EXPOSURE: str = "avg_pm25_exposure"
    AVG_NO2_EXPOSURE: str = "avg_no2_exposure"

    # --- Geospatial ---
    LAT: str = "lat"
    LON: str = "lon"
    CITY: str = "city"
    CITY_ID: str = "city_id"
    COUNTRY: str = "country"

    # --- Environmental registry ---
    BASE_PM25: str = "base_pm25"
    BASE_NO2: str = "base_no2"

    # --- Raw environmental time-series ---
    DATE: str = "date"
    LOCATION: str = "location"
    PM25: str = "pm2_5"
    NO2: str = "no2"

    # --- Engineered features ---
    BMI_CATEGORY: str = "bmi_category"
    AGE_GROUP: str = "age_group"
    POLLUTION_INDEX: str = "pollution_index"
    LIFESTYLE_RISK: str = "lifestyle_risk"
    HIGH_GENOMIC_RISK: str = "high_genomic_risk"

    # --- Split membership ---
    SPLIT: str = "split"  # values: train | val | test

    # --- Derived / dashboard ---
    CALCULATED_RISK_SCORE: str = "calculated_risk_score"
    RISK_CATEGORY: str = "Risk Category"


class Features:
    """
    Ordered list of covariates used in the survival models.

    This list is the single source of truth shared by:
    - src/models/survival_model.R  (via configs/default.yaml)
    - src/visualization/dashboard.py
    - Future: calibration, fairness, robustness modules
    """

    # Survival model covariates — authoritative list.
    # avg_no2_exposure removed: VIF = 15.25 with avg_pm25_exposure.
    # Replaced by pollution_index (combined z-scored burden, fit on train only).
    SURVIVAL_COVARIATES: list[str] = [
        Columns.AGE,
        Columns.IS_SMOKER,
        Columns.GENOMIC_RISK_SCORE,
        Columns.TOWNSEND_INDEX,
        Columns.AVG_PM25_EXPOSURE,
        Columns.POLLUTION_INDEX,
        Columns.LIFESTYLE_RISK,
        Columns.HIGH_GENOMIC_RISK,
    ]

    # Continuous features fed into the sklearn RobustScaler
    CONTINUOUS_FEATURES: list[str] = [
        Columns.AGE,
        Columns.BMI,
        Columns.GENOMIC_RISK_SCORE,
        Columns.TOWNSEND_INDEX,
        Columns.AVG_PM25_EXPOSURE,
        Columns.AVG_NO2_EXPOSURE,
        Columns.LIFESTYLE_RISK,
        Columns.POLLUTION_INDEX,
    ]

    # Binary indicator features — never scaled
    BINARY_FEATURES: list[str] = [
        Columns.IS_SMOKER,
        Columns.HIGH_GENOMIC_RISK,
    ]

    # Categorical features — one-hot encoded in sklearn pipeline
    CATEGORICAL_FEATURES: list[str] = [
        Columns.BMI_CATEGORY,
        Columns.AGE_GROUP,
    ]

    # Columns explicitly excluded from any model (identifiers, geospatial, outcomes)
    NON_FEATURE_COLUMNS: list[str] = [
        Columns.PATIENT_ID,
        Columns.CITY_ID,
        Columns.CITY,
        Columns.COUNTRY,
        Columns.LAT,
        Columns.LON,
        Columns.MONTHS_OBSERVED,
        Columns.EVENT_OCCURRED,
        Columns.SPLIT,
    ]

    # Variables to display in the dashboard telemetry table
    DASHBOARD_DISPLAY_COLUMNS: list[str] = [
        Columns.PATIENT_ID,
        Columns.CITY,
        Columns.AGE,
        Columns.IS_SMOKER,
        Columns.TOWNSEND_INDEX,
        Columns.AVG_PM25_EXPOSURE,
        Columns.GENOMIC_RISK_SCORE,
        Columns.CALCULATED_RISK_SCORE,
        Columns.RISK_CATEGORY,
    ]


class RiskLabels:
    """Category labels for the composite risk score stratification."""

    LOW: str = "Low"
    MODERATE: str = "Moderate"
    HIGH: str = "High"

    ALL: list[str] = [LOW, MODERATE, HIGH]


class SmokerLabels:
    """Human-readable labels for the binary smoking status field."""

    YES: str = "Yes"
    NO: str = "No"

    MAPPING: dict[int, str] = {1: YES, 0: NO}


class EnvPollutants:
    """Display names used in plot axis labels and hover text."""

    PM25_LABEL: str = "PM2.5 (μg/m³)"
    NO2_LABEL: str = "NO₂ (μg/m³)"

    # Hardcoded fallback VIMP values shown in dashboard when
    # outputs/metrics/vimp.csv has not yet been generated by the R model.
    FALLBACK_VIMP: dict[str, float] = {
        "PM2.5 Exposure": 0.35,
        "Polygenic Score": 0.28,
        "Smoking": 0.20,
        "Age": 0.12,
        "Deprivation": 0.05,
    }
