"""
preprocess_features.py
=======================
Stage 3 — Engineer the analytical cohort for survival modelling.

Joins the synthetic clinical cohort with the spatio-temporal environmental
time-series to produce patient-level cumulative exposure features.  Each
patient is randomly assigned to one of the 100 EU cities (using the global
seed for reproducibility), then their mean PM2.5 and NO2 exposures are
computed over their individual observation window.

Geographic scatter (±0.02°) is applied to patient coordinates to prevent
all patients in the same city from overlapping on the map.

Prerequisites
-------------
- ``data/raw/eu_registry.csv``
- ``data/raw/regional_environmental_history.csv``
- ``data/raw/synthetic_clinical_cohort.csv``

All three are generated by the earlier pipeline stages.

Output
------
``data/processed/analytical_cohort.csv``

Usage
-----
    python -m src.feature_engineering.preprocess_features
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from src.utils.config_loader import load_config
from src.utils.constants import Columns
from src.utils.logging_setup import get_logger
from src.utils.paths import DataDirs, DataPaths
from src.utils.seed import set_global_seed

logger = get_logger(__name__)


def _check_inputs() -> None:
    """Raise FileNotFoundError with a helpful message if any input is missing."""
    required = [
        DataPaths.RAW_CLINICAL_COHORT,
        DataPaths.RAW_ENV_HISTORY,
        DataPaths.RAW_REGISTRY,
    ]
    for path in required:
        if not path.exists():
            raise FileNotFoundError(
                f"Required input not found: {path}\n"
                "Ensure all earlier pipeline stages have been run."
            )


def build_analytical_dataset() -> pd.DataFrame:
    """
    Construct the patient-level analytical cohort with engineered exposure features.

    For each patient, this function:
    1. Assigns a random city from the EU registry (seeded deterministically).
    2. Computes mean PM2.5 and NO2 over the patient's observation window.
    3. Adds jittered lat/lon to prevent coordinate overlap on the dashboard map.

    Returns
    -------
    pd.DataFrame
        Analytical cohort ready for survival modelling. Shape: (n_subjects, ~14).

    Side-effects
    ------------
    Writes ``data/processed/analytical_cohort.csv``.

    Raises
    ------
    FileNotFoundError
        If any required input CSV is missing.
    """
    cfg = load_config()
    set_global_seed(cfg.seeds.python)

    logger.info("Aligning %d-city telemetry with clinical cohort...", cfg.study.total_cities)

    _check_inputs()

    clinical_df = pd.read_csv(DataPaths.RAW_CLINICAL_COHORT)
    env_df = pd.read_csv(DataPaths.RAW_ENV_HISTORY)
    registry = pd.read_csv(DataPaths.RAW_REGISTRY)

    logger.info("Loaded %d patients, %d env records, %d city registrations.",
                len(clinical_df), len(env_df), len(registry))

    # Randomly assign each patient to one of the 100 cities
    clinical_df[Columns.CITY_ID] = np.random.choice(
        registry[Columns.CITY_ID], size=len(clinical_df)
    )

    pm25_exposures: list[float] = []
    no2_exposures: list[float] = []
    lats: list[float] = []
    lons: list[float] = []
    city_names: list[str] = []

    for _, patient in clinical_df.iterrows():
        months = max(1, int(patient[Columns.MONTHS_OBSERVED]))
        patient_city_id = patient[Columns.CITY_ID]

        city_meta = registry[registry[Columns.CITY_ID] == patient_city_id].iloc[0]
        city_env = env_df[env_df[Columns.LOCATION] == patient_city_id].head(months)

        pm25_exposures.append(float(city_env[Columns.PM25].mean()))
        no2_exposures.append(float(city_env[Columns.NO2].mean()))

        # Slight coordinate scatter so patients don't fully overlap on map
        lats.append(float(city_meta[Columns.LAT]) + np.random.normal(0, 0.02))
        lons.append(float(city_meta[Columns.LON]) + np.random.normal(0, 0.02))
        city_names.append(str(city_meta[Columns.CITY]))

    clinical_df[Columns.AVG_PM25_EXPOSURE] = pm25_exposures
    clinical_df[Columns.AVG_NO2_EXPOSURE] = no2_exposures
    clinical_df[Columns.LAT] = lats
    clinical_df[Columns.LON] = lons
    clinical_df[Columns.CITY] = city_names

    DataDirs.PROCESSED.mkdir(parents=True, exist_ok=True)
    clinical_df.to_csv(DataPaths.ANALYTICAL_COHORT, index=False)

    logger.info(
        "Success! Engineered analytical dataset (%d patients, %d cities). Written to %s.",
        len(clinical_df),
        cfg.study.total_cities,
        DataPaths.ANALYTICAL_COHORT,
    )
    return clinical_df


if __name__ == "__main__":
    from src.utils.logging_setup import configure_logging
    configure_logging()
    build_analytical_dataset()
